### ISSUE TITLE
Make a text italics

### ISSUE THREAD

**Issue by jethroppaPH** [tallguyjenks/CV#5]
I used your template in preparing my CV. I modified the content of the `data.r` file and added publication. I have a problem, and I cannot find a solution myself, in which I couldn't make a text in italics format. In the title of the paper, there is a scientific name, and as a rule, it must be italicized.

I tried `\emph{Otolithes ruber}` as well as `{\it Otolithes ruber}`, but it throws an error and it stopped the rendering of the PDF.

```
publications <- tribble(
    ~with, ~what, ~why, ~when, ~where,
    "Reproductive biology of Otolithes ruber in XXX", "Name of Journal", "Author1, Author2 & Author3. (20XX). Reproductive biology of Otolithes ruber in XXX. The Journal, XX(i), XX-XX. doi:https://doi.org/xxx", "20XX", "Journal Article"
)
```

Thank you.

**Comment by tallguyjenks** [comment]
i honestly havent played with this in this way. you might need to edit the latex .cls file im not sure
