### ISSUE TITLE
Making font smaller

### ISSUE THREAD

**Issue by Vix-T** [tallguyjenks/CV#7]
Hi there,

Is there a way to make the output font smaller?

Cheers

**Comment by tallguyjenks** [comment]
i havent personally messed with it to try and change font size, but i think you may have luck playing with the `awesome-cv.cls` file

probably this section:

![image](https://github.com/tallguyjenks/CV/assets/29872822/4f4d06c3-646b-49bb-8e4e-68674c771dd2)
